### ISSUE TITLE
sipexer crashes when local address is in use

### ISSUE THREAD

**Issue by arkadiam** [miconda/sipexer#25]
```
# sipexer -register -vl 3 -co -com -ex 60 -fuser alice -cb -ap "abab..." -ha1 -laddr 222.22.10.11:5060  -sd udp:111.22.11.33:5060

[debug] [sipexer.go:705] main.main(): parsed socket address argument ({Val:udp:111.22.11.33:5060 Proto:udp Addr:111.22.11.33 Port:5060 PortNo:5060 AType:4 ProtoId
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b8220]

goroutine 19 [running]:
main.SIPExerSendUDP({{0x7ffd4242984d, 0x16}, {0x737de1, 0x3}, {0x7ffd42429851, 0xd}, {0x7ffd4242985f, 0x4}, 0x13c4, 0x4, ...}, ...)
        /home/dmitry/build/sipexer/sipexer.go:1754 +0x360
created by main.main in goroutine 1
        /home/dmitry/build/sipexer/sipexer.go:780 +0x1836

```
-----
This crash happens when some other app is already binded to 222.22.10.11:5060.

**Comment by rodrigodc** [comment]
Same here.

**Comment by miconda** [comment]
The latest git version prints an error:

```
... bind: address already in use
```
